# Generated by Django 5.2.16 on 2026-08-03 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews_count', models.BigIntegerField(default=0)),
                ('product_url', models.URLField(max_length=2048)),
                ('image_url', models.URLField(max_length=2048)),
                ('search_keyword', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='catalog_product_price_gte_0'), models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 0), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='catalog_product_rating_between_0_5'), models.CheckConstraint(condition=models.Q(('reviews_count__gte', 0)), name='catalog_product_reviews_count_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='SuccessfulProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
                'constraints': [models.UniqueConstraint(fields=('normalized_title', 'category'), name='catalog_successful_title_category_unique')],
            },
        ),
    ]
