# Generated by Django 5.2.16 on 2026-08-03 21:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('product_collection', 'Product collection'), ('trend_collection', 'Trend collection'), ('product_analysis', 'Product analysis')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status', '-created_at'], name='an_job_type_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('boost_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('baseline_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='catalog.product')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('final_score__gte', 0), ('final_score__lte', 100)), name='analytics_analysis_final_between_0_100')],
            },
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=16)),
                ('period', models.CharField(max_length=64)),
                ('current_interest', models.SmallIntegerField()),
                ('average_interest', models.SmallIntegerField()),
                ('growth_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('series', models.JSONField(blank=True, default=list)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='catalog.product')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['product', '-collected_at'], name='an_trend_product_collected_idx'), models.Index(fields=['keyword', 'geo', 'period'], name='an_trend_query_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_interest__gte', 0), ('current_interest__lte', 100)), name='analytics_trend_current_between_0_100'), models.CheckConstraint(condition=models.Q(('average_interest__gte', 0), ('average_interest__lte', 100)), name='analytics_trend_average_between_0_100')],
            },
        ),
    ]
